openapi: 3.0.1
info:
  title: DIA
  description: Decentralized Intelligence Agency
  termsOfService: http://swagger.io/terms/
  contact:
    email: shaokexu@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://localhost:9099/
tags:
- name: soi
  description: Service of Intelligence
- name: dia
  description: Decentralized Intelligence Agency
- name: intelligences
  description: Intelligences want to collect
paths:
  /apis/sois:
    post:
      tags:
        - soi
      summary: Register a SOI. 
      description: Operation Index - 0001
      operationId: registerSOI
      requestBody:
        description: Need to register SOI information
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SOI'
      responses:
        200:
          description: Registered successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    description: Generate MongoDB Id
                  global_id:
                    $ref: '#/components/schemas/GlobalId'
        400:
          description: Bad request, the data pass isn't valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /apis/sois/{gid}:
    get:
      tags:
        - soi
      summary: Get a SOI. 
      description: Operation Index - 0002
      operationId: getSOI
      parameters:
        - in: path
          name: gid
          required: true
          description: global_id of SOI
          schema:
            $ref: '#/components/schemas/GlobalId'
      responses:
        200:
          description: Get a SOI successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOI'
        400:
          description: Bad request, the data pass isn't valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Cannot find specific SOI
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - soi
      summary: Update a SOI
      description: Operation Index - 0003
      operationId: updateSOI
      parameters:
        - in: path
          name: gid
          required: true
          description: global_id of SOI
          schema:
            $ref: '#/components/schemas/GlobalId'
      requestBody:
        description: SOI information need to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SOI'
      responses:
        204:
          description: Update SOI successful
        404:
          description: Cannot find specific SOI
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - soi
      summary: Unregister a SOI
      description: Operation Index - 0004
      operationId: unregisterSOI
      parameters:
        - in: path
          name: gid
          required: true
          description: global_id of SOI
          schema:
            $ref: '#/components/schemas/GlobalId'
      responses:
        200:
          description: Delete SOI successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  global_id:
                    $ref: '#/components/schemas/GlobalId'
        404:
          description: Cannot find specific SOI
          content:
            application/json:
              schema:
                type: object
                properties:
                  global_id:
                    $ref: '#/components/schemas/GlobalId'
  /apis/sois/{gid}/status:
    put:
      tags:
        - soi
      summary: Update a SOI status 
      description: Operation Index - 0010
      operationId: updateSOIStatus
      parameters:
        - in: path
          name: gid
          required: true
          description: global_id of SOI
          schema:
            $ref: '#/components/schemas/GlobalId'
      responses:
        200:
          description: Update a SOI successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SOI'
        400:
          description: Bad request, the data pass isn't valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Cannot find specific SOI
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /apis/intelligences:
    get:
      tags:
        - intelligences
      summary: Get intelligences for agents to collect
      description: Operation Index - 0005
      operationId: getIntelligences
      parameters:
        - in: query
          name: type
          required: true
          description: Agent Type
          schema:
            type: string
            enum: 
              - browserExtension
              - headlessBrowser
              - service
        - in: query
          name: gid
          required: true
          description: Agent Global Id
          schema:
            $ref: '#/components/schemas/GlobalId'
        - in: query
          name: limit
          description: How many intelligences want to get
          schema:
            type: number
      responses:
        200:
          description: Intelligences for collected
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Intelligence'
    post:
      tags:
        - intelligences
      summary: Add intelligences to collecting list
      description: Operation Index - 0006
      operationId: addIntelligences
      requestBody:
        description: Need to collect intelligences
        required: true
        content:
          application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Intelligence'
      responses:
        200:
          description: Extract intelligences successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddSuccess'
        404:
          description: Cannot find specific SOI, please make sure you registered
    put:
      tags:
        - intelligences
      summary: Update intelligences
      description: Operation Index - 0007
      operationId: updateIntelligences
      requestBody:
        description: Update intelligences
        required: true
        content:
          application/json:
              schema:
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/Intelligence'
                    - type: object
                      properties:
                        operation:
                          type: string
                          description: what kind of operation want to do to this intelligence. This will not be save to Intelligence.
                          default: DELETE
                          enum:
                            - DELETE
                            - UPDATE
      responses:
        200:
          description: Extract intelligences successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddSuccess'
        404:
          description: Cannot find specific SOI, please make sure you registered
    delete:
      tags:
        - intelligences
      summary: Delete intelligences from collecting list
      description: Operation Index - 0008
      operationId: deleteIntelligences
      parameters:
        - in: query
          name: gids
          description: Intelligences' Global Id that want to delete
      responses:
        204:
          description: Update SOI successful
  /health:
    get:
      tags:
        - dia
      summary: Check DIA's health status
      description: Operation Index - 0009
      operationId: checkHealth
      responses:
        200:
          description: SOI is active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
components:
  schemas:
    GlobalId:
        type: string
        format: base64
        description: Global unique id.
        example: ef72448b-7bc4-42d1-9436-822c9634d943
    AddSuccess:
      type: object
      properties:
        successful:
          type: array
          description: Successful Intelligence global_id
          items:
            $ref: '#/components/schemas/GlobalId'
        fail:
          type: array
          description: Fail Intelligence global_id
          items:
            $ref: '#/components/schemas/GlobalId'   
    SOI:
      type: object
      required:
        - global_id
      properties:
        global_id:
          $ref: '#/components/schemas/GlobalId'
        soi_name:
          type: string
          description: The name of SOI
        api_key:
          type: string
          description: API key that used to access SOI
        base_url:
          type: string
          description: Base URL for RESTFul APIs
        status:
          type: string
          description: SOI status
          enum:
            - ACTIVE
            - INACTIVE
        health:
          type: object
          description: RESTFul API for check server's health status
          properties:
            method:
              type: string
              default: 'GET'
              description: HTTP request method
              enum:
                - GET
                - POST
                - PUT
                - DELETE
            path:
              type: string
              format: uri
              default: '/apis/health'
              description: path of RESTFul API for check server's health status
        callback:
          type: object
          description: RESTFul API for collected intelligences
          properties:
            method:
              type: string
              default: 'POST'
              description: HTTP request method
              enum:
                - GET
                - POST
                - PUT
                - DELETE
            path:
              type: string
              format: uri
              default: '/apis/intelligences'
              description: path of RESTFul API for check server's health status
    Intelligence:
      type: object
      description: Intelligence that agents collected
      required:
        - global_id
        - soi_gid
        - url
      properties:
        global_id:
          $ref: '#/components/schemas/GlobalId'
        soi:
          $ref: '#/components/schemas/SOI'
        priority:
          type: number
          description: Priority of this intelligence.
        created_at:
          type: number
          description: Timestamp. When this intelligence job was created
          example: 1553974629109
        modified_at:
          type: number
          description: Timestamp. When this intelligence job was modified
          example: 1553974629109
        last_collected_at:
          type: number
          description: Timestamp. Last time collect this intelligence.
          example: 1553974629109
        started_at:
          type: number
          description: Timestamp. When this intelligence started to be collected
          example: 1553974619655
        ended_at:
          type: number
          description: Timestamp. When this intelligence finished collect
          example: 1553974629109
        status:
          type: string
          description: Status of this intelligence
          default: CONFIGURED
          enum:
            - CONFIGURED
            - FINISHED
            - RUNNING
            - FAILED
            - PAUSED
            - TIMEOUT
        suitable_agents:
          type: array
          default:
            - browserExtension
          items: 
            type: string
            enum:
              - browserExtension
              - headlessBrowser
              - service
        url:
          type: string
          description: Which URL need to collect intelligence
          format: uri
          example: https://json-schema.org
        data:
          type: object
          description: Collected intelligence data. It can be object, array, string, number ...
          properties:
            url:
              type: string
              description: Which URL need to collect intelligence
              format: uri
              example: https://json-schema.org
            data:
              type: object
              description: Collected intelligence data. It can be object, array, string, number ...
        metadata: 
          type: object
          description: Additional metadata for this intelligence
          properties:
            script:
              type: string
              description: Code want to execute after **window.onload**. You only need to pass function body. 
                And Default you will get following parameters - **resolve**, **reject**, **intelligence**, **axios**. 
                You need to resolve(data) or reject(err), and will send data or err to SOI.
                If you need agent to execute your code. Only work with **browserExtension** and **headlessBrowser** agent
        agent:
          $ref: '#/components/schemas/Agent'
              
    HealthStatus:
      type: object
      properties:
        name:
          type: string
          description: DIA Name
          example: "dia"
        description:
          type: string
          description: DIA description.
          example: "Decentralized Intelligence Agency"
        version:
          type: string
          description: DIA version
          example: "0.0.1"
        migrationVersion:
          type: string
          description: DIA currently migrationVersion
          example: 1
    Error:
      type: object
      properties:
        stack:
          type: string
          description: Error stack, return to UI only in develop mode
        message:
          type: string
          description: Error Message
        statusCode:
          type: number
          description: HTTP Status Code
        code:
          type: string
          description: Error Code
        data:
          type: object
          description: Additional data for this error
    Agent:
      type: object
      properties:
        global_id:
          $ref: '#/components/schemas/GlobalId'
        status:
          type: string
          description: Agent status
          enum:
            - ACTIVE
            - INACTIVE
        type:
          type: string
          description: Agent type
          enum:
            - browserExtension
            - headlessBrowser
            - service
        started_at:
          type: number
          description: Timestamp. When this intelligence started to be collected
          example: 1553974619655
        ended_at:
          type: number
          description: Timestamp. When this intelligence finished collect
          example: 1553974629109
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header  